### ISSUE TITLE
Test App for NewHandWave

### ISSUE THREAD

**Issue by SnehPandya18** [jtkac/NewHandwave#2]
Hello there,

I am using your updated library in my test app. I have successfully completed the setup steps given in ReadMe.md.

I have only `MainActivity.java` file in my test app and I have implemented `CameraGestureSensor.Listener` in my `MainActivity.java` .

![image](https://cloud.githubusercontent.com/assets/16193823/22883674/465a0a72-f217-11e6-8abc-7ec5d1e76dab.png)

As shown in the screenshot, I want to test & detect hand wave gestures as well as hand click gesture. For that I have used `LocalOpenCV` with 3 parameters.

Unfortunately, Even after referring to implementation of the method and documentation provided, I am not able to understand what to pass as 2nd and 3rd parameter. Please help me with that. What steps do I need to follow to successfully run this? Do I need to create any other activity/fragment for that and call it in the `loader`? Please also provide the steps for the same.

Help is very much appreciated.

**Comment by jtkac** [comment]
Hello,

In the statements:

    LocalOpenCV loader = new LocalOpenCV(MainActivity.this, null);

or

    LocalOpenCV loader = new LocalOpenCV(MainActivity.this, CameraGestureSensor.Listener, ClickSensor.Listener);

should both be this:

    //pass in the context of your activity, and the listeners implemented.
    LocalOpenCV loader = new LocalOpenCV(MainActivity.this, MainActivity.this, MainActivity.this);
    // also can just use this:
    // LocalOpenCV loader = new LocalOpenCV(this, this, this);

Reason Being is that you have implemented those interface methods in your activity. Just passing in the reference to the activity should be good enough.

**Comment by SnehPandya18** [comment]
Working like a charm! Thank you! 👍
